categories:
  mpcVidply: ~
  mpcVidply.accessibility:
    parent: mpcVidply

settings:
  mpcVidply.screenReaderAnnouncements:
    default: true
    type: bool
    category: mpcVidply.accessibility
  mpcVidply.resumePlayback:
    default: false
    type: bool
    category: mpcVidply
